version: "3.8"
services:
  app:
    container_name: app
    command: bash -c "cd app/ && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always

  redis:
    container_name: redis
    image: redis:6.2-alpine

  celery_worker:
    container_name: celery_worker
    build: .
    command: bash -c "cd app/ && celery -A celery_worker.celery worker --loglevel=info"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: bash -c "cd app/ && celery -A celery_worker.celery flower --port=5555"
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
      - celery_worker